# Bioarchitettura® Website Configuration
# GitHub Pages Jekyll Configuration

title: "Bioarchitettura® - Abitare la Terra"
description: "La prima rivista italiana di Bioarchitettura. 30 anni di eccellenza nell'architettura ecologica e sostenibile."
url: "https://hannesmitterer.github.io"
baseurl: "/bioarchittetura"

# Site settings
lang: it
timezone: Europe/Rome
author: "Fondazione Italiana per la Bioarchitettura®"
email: "info@bioarchitettura.org"
phone: "+39 0471 973097"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for CMS-like functionality
collections:
  rivista:
    output: true
    permalink: /:collection/:name/
  master:
    output: true
    permalink: /:collection/:name/
  news:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "rivista"
    values:
      layout: "rivista"
  - scope:
      path: ""
      type: "master"
    values:
      layout: "master"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"

# SEO settings
google_analytics: # Add your GA tracking ID here
social:
  name: "Bioarchitettura®"
  links:
    - https://www.facebook.com/bioarchitettura
    - https://www.instagram.com/bioarchitettura
    - https://www.linkedin.com/company/bioarchitettura

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache

# Include files
include:
  - _pages

# Sass configuration
sass:
  style: compressed
  load_paths:
    - assets/css

# Pagination
paginate: 6
paginate_path: "/news/page:num/"

# Site data
rivista:
  founded: 1992
  founders: 
    - "Ugo Sasso"
    - "Wittfrida Mitterer"
  editions: 152
  years: 30
  articles: 1699
  authors: 1254
  collaboration: "Dipartimento di Architettura dell'Università di Bologna"

# Shop settings
shop:
  subscription_price: "€45/anno"
  ebook_price_range: "€15-25"
  book_price_range: "€30-50"
  shipping: "Spedizione gratuita"

# Contact information
contact:
  foundation_name: "Fondazione Italiana per la Bioarchitettura® e l'Antropizzazione Sostenibile dell'Ambiente"
  organization_type: "Ente morale senza fini di lucro"
  phone: "+39 0471 973097"
  email: "info@bioarchitettura.org"
  
# Social media links
social_links:
  facebook: "#"
  instagram: "#"
  linkedin: "#"
  
# Mission statement
mission: "È diffondere gli approcci progettuali che privilegiano la relazione e l'incontro, il benessere, l'equità grazie a una nuova cultura capace di integrare percezione e sostenibilità, analisi e partecipazione, tecnica e organizzazione."