# Bioarchitettura® - Jekyll Configuration
title: "Bioarchitettura® - Abitare la Terra"
description: "La rivista italiana di riferimento per l'architettura sostenibile, l'edilizia ecologica e la progettazione bioclimatica dal 1990."
baseurl: "/bioarchittetura"
url: "https://hannesmitterer.github.io"
author: "Fondazione Italiana per la Bioarchitettura®"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: Europe/Rome

# GitHub Pages compatible plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  rivista:
    output: true
    permalink: /rivista/:name/
  master:
    output: true
    permalink: /master/:name/
  news:
    output: true
    permalink: /news/:name/

# Default values for collections
defaults:
  - scope:
      path: ""
      type: "rivista"
    values:
      layout: "rivista"
      author: "Redazione Bioarchitettura®"
  - scope:
      path: ""
      type: "master"
    values:
      layout: "master"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"

# SEO and social
social:
  name: "Bioarchitettura® - Abitare la Terra"
  links:
    - https://www.facebook.com/bioarchitettura
    - https://www.instagram.com/bioarchitettura
    - https://www.linkedin.com/company/bioarchitettura

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Gemfile.github
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - admin/

# GitHub Pages settings
safe: true
incremental: false