---
name: Bug Report
about: Report a bug or issue with the website
title: '[BUG] Brief description of the issue'
labels: ['bug', 'needs-triage']
assignees: []

---

## 🐛 Bug Report

### Description
A clear and concise description of what the bug is.

### Steps to Reproduce
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected Behavior
A clear and concise description of what you expected to happen.

### Actual Behavior
A clear and concise description of what actually happened.

### Screenshots
If applicable, add screenshots to help explain your problem.

### Environment Information
- **Device**: [e.g. Desktop, Mobile]
- **OS**: [e.g. iOS, Windows, Linux]
- **Browser**: [e.g. Chrome, Safari, Firefox]
- **Version**: [e.g. 22]
- **Screen Size**: [e.g. 1920x1080, Mobile 375x667]

### Additional Context
Add any other context about the problem here.

### Checklist
- [ ] I have searched for existing issues before creating this one
- [ ] I have provided all the requested information
- [ ] I have tested this on the latest version of the website