name: Link Checker

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Check links weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          cache-version: 0
          
      - name: Build Jekyll site
        run: bundle exec jekyll build --baseurl ""
        env:
          JEKYLL_ENV: production
          
      - name: Check internal links in HTML files
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/mlc_config.json'
          folder-path: '_site'
          file-extension: '.html'
          
      - name: Check external links in Markdown files
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/mlc_config.json'
          folder-path: '.'
          file-extension: '.md'
          
      - name: Link Checker Results
        if: failure()
        run: |
          echo "::error::Some links are broken. Please check the logs above for details."
          echo "Fix the broken links and push the changes to resolve this issue."